name: "Homemate Bridge"
description: "A bridge for Homemate devices to Home Assistant"
version: "0.0.1"
slug: "homemate_bridge"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386

ports:
  10001/tcp: 10001
ports_description:
  10001/tcp: "Homemate Bridge Port"
schema:
  keys: str
  devices: str?
  homemate_port: int?
  mqtt_client_id: str?
  mqtt_username: str
  mqtt_password: str
  mqtt_host: str
  mqtt_port: int
  mqtt_tls_cacert: str?
  mqtt_tls_certfile: str?
  mqtt_tls_keyfile: str?
  discovery_prefix: str?
  node_id: str?
